name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  validate:
    uses: kVinayak58/platform-config/.github/workflows/terraform-ci.yml@main
